### PR TITLE
Fixed build

### PR DESCRIPTION
**Pull request by guyluz11**

### CODE REVIEW

**Review by bostick — APPROVED** [review]

**Comment by bostick** [comment]
Thank you for this! I have not looked at this in a long time and it is good to get it building again.

**Comment by guyluz11** [comment]
Sure 😁

I am new to OpenGL and trying to run some old project, searched for other projects as a reference why it doesn't run.


If you would like to get in touch take a look it will be nice.

**Comment by bostick** [comment]
Sure, I can take a look.

**Comment by guyluz11** [comment]
Sent you an invite to the private repo

**Pull request merged**
